image: nexus.esphere.local:5000/ubuntu:20.04

before_script:
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

deploy:
  stage: deploy
  script:
    - echo "pull changes to 172.17.229.9"
    - echo "${SSH_KEY}" > ssh_key; chmod 600 ssh_key
    - apt update ; apt install openssh-client -y
    - ssh -o StrictHostKeyChecking=no -o BatchMode=yes  -i ssh_key titaev.ab@172.17.229.9 "cd /home/titaev.ab/test; git pull"

